apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: donut-example
  name: donut
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: donut-example
replicas: 2
template:
  metadata:
    labels:
      app.kubernetes.io/name: donut-example
  spec:
    containers:
      - image: ghcr.io/djnavarro/donut
      name: donut
      ports:
        - containerPort: 80
